# -*- coding: utf-8 -*-
"""dlt-workshop-homework.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bFYqrw0NEqqdUl7HSsLZbuJ-lnoQsx65

# LLM Zoomcamp 2025 -DLT Workshop Homework
"""

!pip install -q "dlt[qdrant]" "qdrant-client[fastembed]"

!dlt --version

"""## Question 1: What's the version of dlt that you installed?

**Answer**:  dlt 1.12.3

## Question 2. dlt pipeline
"""

import requests

@dlt.resource
def zoomcamp_data():
    docs_url = 'https://github.com/alexeygrigorev/llm-rag-workshop/raw/main/notebooks/documents.json'
    docs_response = requests.get(docs_url)
    documents_raw = docs_response.json()

    for course in documents_raw:
        course_name = course['course']

        for doc in course['documents']:
            doc['course'] = course_name
            yield doc

from dlt.destinations import qdrant

qdrant_destination = qdrant(
  qd_path="db.qdrant",
)

import dlt


pipeline = dlt.pipeline(
    pipeline_name="zoomcamp_pipeline",
    destination=qdrant_destination,
    dataset_name="zoomcamp_tagged_data"

)
load_info = pipeline.run(zoomcamp_data())
print(pipeline.last_trace)

"""**Answer**: 948

## Question 3. Embeddings
"""

import json

with open('/content/db.qdrant/meta.json', 'r') as json_file:
  data = json.load(json_file)

data

"""**Answer**: fast-bge-small-en"""